### ISSUE TITLE
use ungh

### ISSUE THREAD

**Issue by ryoppippi** [WarningImHack3r/svelte-changelog#21]
First, thank you for creating this awesome page
### What problem are you trying to solve?

When I browse the issues and releases, I face the issue like 
`API rate limit exceeded`.

### Describe the solution you’d like

Use [ungh](https://github.com/unjs/ungh) instead of raw github api

### Describe any alternatives you’ve also considered

If it sounds good for you, I'll create a PR

**Comment by WarningImHack3r** [comment]
> First, thank you for creating this awesome page

You're welcome! :)

> When I browse the issues and releases, I face the issue like `API rate limit exceeded`.

I'm aware of this problem and recently added caching to mitigate that for the main page. I can’t make the GraphQL API work without being instantly rate-limited; however, the threshold for the REST API is much higher and usually sufficient for regular usage on prod. For dev, you can provide your own GH token.

How many pages do you visit and on which pages do you encounter errors?

> Use [ungh](https://github.com/unjs/ungh) instead of raw github API [...] If it sounds good for you, I'll create a PR

I didn't know about that! It looks interesting, _however_:
- I'm using the Octokit package, and such an abstraction would require some refactoring to transition to raw fetch calls
- We'd still need the Octokit package for types
- Ungh doesn't provide a solution for GraphQL endpoints
- Even without all that, Ungh doesn't provide some endpoints I need, like the `.../pulls/:id` endpoint

That said, creating a (typed) wrapper around endpoints fetching is possible, which would be a hybrid of Ungh, Octokit, and Octokit GraphQL. It’d _slightly_ increase the threshold before getting rate-limited, even though the lack of the `pulls` endpoint makes such a refactor not very useful in my opinion.

You can still draft a PR if you want though, which we would improve over time to use the NPM package of Ungh and implement new cached endpoints as they become available.  
I would just like to make sure that Ungh won't die anytime soon and will eventually improve someday (NPM package, new endpoints), without which this whole refactor won't be very useful. I quickly saw that the issue they have mentioning the NPM package is more than 2 years old, which doesn't look promising, unfortunately.

**Comment by ryoppippi** [comment]
Ok got it thanks
