### ISSUE TITLE
Other releases page not showing

### ISSUE THREAD

**Issue by shinokada** [WarningImHack3r/svelte-changelog#31]
### What is the issue?

https://svelte-changelog.vercel.app/?tab=others page shows a loading spinner.

![image](https://github.com/user-attachments/assets/32c28d28-5918-492c-ab5c-f76ce50a9975)

### What are the steps to reproduce this issue?

Go to [Other releases](
![image](https://github.com/user-attachments/assets/8c5ced3d-4661-454b-85a8-1b9b9d1f09d2)
)

### What were you expecting to happen?

Show the page.

### What OS are you experiencing the problem on?

macOS

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
It’s likely a rate limit issue, can you check the console?

**Comment by shinokada** [comment]
![image](https://github.com/user-attachments/assets/df206f42-8311-4bc8-8371-6461d07ff43a)

**Comment by WarningImHack3r** [comment]
It's a rate-limit issue due to too many requests to the GH API; you'll have to log in to bypass that!

**Comment by shinokada** [comment]
Ok, thanks. It works after logged in.
